a

diff --git a/.circleci/config copy.yml b/.circleci/config copy.yml
--- a/.circleci/config copy.yml
+++ b/.circleci/config copy.yml
@@ -7,11 +7,11 @@ commands:
         # Add parameter here   
         steps:
           - run:
-              name: Destroy environments
-              when: on_fail
-              command: |
-                # Your code here
-                exit 1
+            name: Destroy environments
+            when: on_fail
+            command: |
+              # Your code here
+              exit 1
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
@@ -19,18 +19,18 @@ commands:
       # Add parameter here     
       steps:
         - run:
-            name: Revert migrations
-            # Add when this will run
-            command: |
-              # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-              SUCCESS = 1
-              if(( $SUCCESS==1 )); 
-              then
-              #  cd ~/project/backend
-              #  npm install
-              #  Add revert code here. You can find this in the Getting Started section.
-                exit 1
-              fi
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
+            then
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              exit 1
+            fi
             
 jobs:
   build-frontend:
@@ -41,10 +41,10 @@ jobs:
         - restore_cache:
             keys: [frontend-build]
         - run:
-              name: Build front-end
-              command: |
-                # Your code here
-                exit 1
+            name: Build front-end
+            command: |
+              # Your code here
+              exit 1
         - save_cache:
             paths: [frontend/node_modules]
             key: frontend-build
@@ -57,10 +57,10 @@ jobs:
       - restore_cache:
           keys: [backend-build]
       - run:
-            name: Back-end build
-            command: |
-              # Your code here
-              exit 1
+          name: Back-end build
+          command: |
+             # Your code here
+             exit 1
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -103,28 +103,28 @@ jobs:
     steps:
       # Checkout code from git
       - run:
-            name: Ensure back-end infrastructure exists
-            command: |
-              aws cloudformation deploy \
-                --template-file .circleci/files/backend.yml \
-                #--tags project=your-tag \
-                # --stack-name "your back-end stack name with workflow id" \
-                # --parameter-overrides ID="your workflow id"  
-                exit 1
-      - run:
-            name: Ensure front-end infrastructure exist
-            command: |
-              aws cloudformation deploy \
-                --template-file .circleci/files/frontend.yml \
-                #--tags project=your-tag \
-                # --stack-name "your front-end stack name with workflow id" \
-                # --parameter-overrides ID="your workflow id"  
-                exit 1
-      - run:
-            name: Add back-end ip to ansible inventory
-            command: |
-              # Your code here
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              #--tags project=your-tag \
+              # --stack-name "your back-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
               exit 1
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              #--tags project=your-tag \
+              # --stack-name "your front-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              exit 1
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            # Your code here
+            exit 1
       - persist_to_workspace:
           root: ~/
           paths:
@@ -139,15 +139,15 @@ jobs:
       # Add ssh keys with fingerprint
       # attach workspace
       - run:
-            name: Install dependencies
-            command: |
-              # Your code here
-              exit 1
+          name: Install dependencies
+          command: |
+            # Your code here
+            exit 1
       - run:
-            name: Configure server
-            command: |
-              # Your code here
-              exit 1
+          name: Configure server
+          command: |
+            # Your code here
+            exit 1
       # Here's where you will add some code to rollback on failure      
 
   run-migrations:
@@ -156,15 +156,15 @@ jobs:
     steps:
       # Checkout code from git
       - run:
-            name: Run migrations
-            command: |
-              # Your code here
-              exit 1
+          name: Run migrations
+          command: |
+            # Your code here
+            exit 1
       - run:
-            name: Send migration results to memstash
-            command: |
-              # Your code here
-              exit 1
+          name: Send migration results to memstash
+          command: |
+            # Your code here
+            exit 1
      # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
@@ -173,20 +173,20 @@ jobs:
     steps:
       # Checkout code from git
       - run:
-            name: Install dependencies
-            command: |
-              # your code here
+          name: Install dependencies
+          command: |
+            # your code here
       - run:
-            name: Get backend url
-            command: |
-              # your code here
-              export API_URL="http://${BACKEND_IP}:3030"
-              echo "${API_URL}"
+          name: Get backend url
+          command: |
+            # your code here
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
       - run:
-            name: Deploy frontend objects
-            command: |
-              # your code here
-        # Here's where you will add some code to rollback on failure      
+          name: Deploy frontend objects
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure      
                     
   deploy-backend:
     docker:
@@ -196,14 +196,14 @@ jobs:
       # Add ssh keys with fingerprint
       # attach workspace
       - run:
-            name: Install dependencies
-            command: |
-              # your code here
+          name: Install dependencies
+          command: |
+            # your code here
       - run:
-            name: Deploy backend
-            command: |
-              # your code here
-        # Here's where you will add some code to rollback on failure  
+          name: Deploy backend
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
   smoke-test:
     docker:
@@ -211,22 +211,22 @@ jobs:
     steps:
       # Checkout code from git
       - run:
-            name: Install dependencies
-            command: |
-              # your code here
+          name: Install dependencies
+          command: |
+            # your code here
       - run:
-            name: Get backend url
-            command: |
-              # your code here
+          name: Get backend url
+          command: |
+            # your code here
       - run:
-            name: Backend smoke test.
-            command: |
-              # your code here
+          name: Backend smoke test.
+          command: |
+            # your code here
       - run:
-            name: Frontend smoke test.
-            command: |
-              # your code here
-        # Here's where you will add some code to rollback on failure  
+          name: Frontend smoke test.
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
     docker:
@@ -234,14 +234,14 @@ jobs:
     steps:
       # Checkout code from git
       - run:
-            name: Install dependencies
-            command: |
-              # your code here
+          name: Install dependencies
+          command: |
+            # your code here
       - run:
-            name: Update cloudfront distribution
-            command: |
-              # your code here
-        # Here's where you will add some code to rollback on failure  
+          name: Update cloudfront distribution
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
 cleanup:
     docker:
@@ -249,18 +249,18 @@ cleanup:
     steps:
       # Checkout code from git
       - run:
-            name: Get old stack workflow id
-            command: |
-              # your code here
-              export OldWorkflowID="the id here"
-              export STACKS=[] #put the list of stacks here
+          name: Get old stack workflow id
+          command: |
+            # your code here
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
       - run:
-            name: Remove old stacks and files
-            command: |
-              if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-              then
-                # your code here
-              fi
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              # your code here
+            fi
             
 
 workflows:
